CtbGui.py
CtbGui.ui

As the initial GUI is complete, I think we should merge it to the main branch and follow up on the updates and changes.

Initial GUI

---

CtbGui.py

- fixed some incorrect starting up or ending of bit numbers. 
- requires new server from developer for better error message
- requires handling of exceptions (another PR)... to show that it cannot set adcenable for eg. to 0.

adc buttons does what it should do

---

CtbGui.ui

fixed maximum wait time to 999999

waittime max

---

CtbGui.py
CtbGui.ui

- non blocking acquire in ctb gui (requres allow_nonblocking_1gb_ctb server)
- also stop works from gui now
- start disabled when starting and reenabled when done
- when done also stops reciever
- show status 
- connected image
- progress bar

3) Non blocking acquire, status, image, progressbar

---

CtbGui.py
CtbGui.ui

Refresh tabs if clicked. grouped into functions

4) Tab refresh

---

CtbGui.py
CtbGui.ui
bit_utils.py

motivation: signals disconnected before updating the fields with values
- reorganized to keep track of this
- form changes (removing blue background that are for just some frames), reorganizing pattern tab for space and others for better readability
- disabling plot checkbox and plot push button if (adc not enabled or not in dbitlist)
- default random color for push button

1. Fix slots on refresh

---

CtbGui.py
CtbGui.ui

handling exceptions to validate hex input for addresses in qlineedit

7. Add except handle hex lineedit

---

CtbGui.py

- fix checkbox and qlineedit slots (multiple events, still doesnt solve previous one)
- read_timer to go on forever, else if stopped at end of acq, next acquiistion will get the dummy packet

1. fix signals for checkbox

---

CtbGui.py
CtbGui.ui

- display measured currents in power supplies tab, along with a button to power off all the voltages 
- changed display from set voltage to measured voltage, spinbox only shows set voltage
- button enabled only when any one voltage up
- setting voltage or power of button, calls get voltage, get current, get vchip, disable power button

Power currents

---

CtbGui.py
CtbGui.ui

- show pattern viewer if view pattern clicked
- show waveform/image plot if acquire or stop clicked
- hide analog or digital plot according to readout
- shift + enter shortcut to start acquiistion from any tab
- ctrl + c now works to abort the gui

Switching plots

---

CtbGui.py
CtbGui.ui

- square waveforms for digital mode (stepMode = left)

digital plot

---

CtbGui.py
CtbGui.ui
defines.py

- transceiver (romode, transceiverenable, tsamples)
- image, waveform plot
- color plot
-keyboard short cuts (ctrl +, ctrl -, shit return) to move tab left and right or start acquisition from any tab, keyboard shortcuts menu
- waveform plots appear as the signals/adc/transceiver chosen in plot and also depending on readout mode
- custom built function to "show plot values" for imageviews

Transceiver

---

CtbGui.py
defines.py

2. Moenchimage

---

CtbGui.py

rotate moench 04 image by 90 and allow zooming in by selecting an area using left mouse button

pan and rotate

---

CtbGui
CtbGui.ui
defines.py

added color map, options and frame number above the image
moved checks about moench image or matterhorn image requirements to before starting acquisition

color map, findex

---

.clang-format
CtbGui
Makefile
decoder.py
pixelmap.py
setup.py
src/decoder.c
src/pm_decode.c
src/pm_decode.h
src/thread_utils.h
tests/test_decoder.py

- added the decode module
- created an _decode e extension
- added pixelmaps

Moving decoding to a c extension

---

CtbGui

- remember settings of main window size and position
- dockwidget if docked, its size and position as well
- then update it next time the gui is opened

settings for window sizes

---

CtbGui
CtbGui.ui
decoder.py
pixelmap.py
src/decoder.c
src/pm_decode.c
tests/test_decoder.py

- connected c decoder
- fixed gui to show all tabs by increasing width of central widget

using c decoder for moench 04 and matterhorn

---

CtbGui

update row and col when choosing image type, neeeded to show values

fix show values

---

CtbGui
CtbGui.ui
plotPattern.py

keep the range selected for every new acquisition

disable resetting colormap values

---

CtbGui
TabClasses/DACs.py

PR#2 containing refactoring of: slow ADCs Tab + DACs Tab

Refactor DACs tab (PR#2)

---

pyctbgui/__init__.py
tests/test_bit_utils.py
tests/test_decoder.py

Added some simple tests for the bit_utils. (can be run using make test)
@thattil @Bechir-Brahem 
Open question can we find a better name for manipulate_bit?

added simple tests for bit_utils

---

pyctbgui/ui/CtbGui.ui
pyctbgui/ui/Dacs.ui

fix dacs ui position

---

pyctbgui/ui/CtbGui.ui
pyctbgui/ui/Dacs.ui
pyctbgui/ui/plot.ui

fix a bug where you can select multiple radio buttons in the plot tab
merged with #133

group radio buttons

---

pyctbgui/services/Plot.py
pyctbgui/services/PowerSupplies.py
pyctbgui/services/Signals.py
pyctbgui/ui/CtbGui.ui
pyctbgui/ui/Dacs.ui
pyctbgui/ui/MainWindow.py
pyctbgui/ui/plot.ui
pyctbgui/utils/__init__.py

resolve comments in split ui file PR#1 #126 
merged with #135

finalize split ui file

---

MANIFEST.in
Makefile
pyctbgui/utils/decoder.py
setup.py

- sdist works (no missing headers)
- wheel includes _decoder
- added optional dev requirements (not sure about this one)

Improved setup.py 

---

.github/workflows/build-and-test-inplace.yml
CtbGui
Makefile
pyctbgui/__init__.py
pyctbgui/ui/__init__.py

Tests one of our two workflows (inplace builds). 
The action:
- Runs for python 3.10 and 3.11
- build C extension
- runs tests

Added github action to build in source directory 

---

pyctbgui/services/DACs.py

fix disabled dac issue

---

pyctbgui/services/Signals.py

error: BIT0_31_MASK is not found in Defines

fix un-updated line after refactoring Defines

---

pyctbgui/services/Plot.py
pyctbgui/ui/MainWindow.py

save plot and detector type in QT QSettings when closing the window and restore them after opening the window again

save plot type PR#4
